### PR TITLE
Fixed cursor focus bugginess. Closes #2

### LINKED ISSUE #2: Add an auto-focus parameter to the API
Right now the shell seems to focus cursor on last added input. It would be nice to be able to tell it which input is important to focus on.

### PR DESCRIPTION
**Pull request by imathis**
- By default customInput fields are only focused when toggled on.
- Added a focus attribute, enabling auto-focus upon addition to the dom.
- Fixed issue where nested fields would focus improperly.

### CODE REVIEW

File: compose-shell-param.js [hunk 1]
```diff
@@ -137,7 +138,7 @@ xtag.register('compose-shell-param', {
   },
 
   methods: {
-    toggle: function(){ this.visible = !this.visible },
+    toggle: function(){ this.add = true; this.visible = !this.visible },
```
Comment (jeromegn) [inline compose-shell-param.js]: Can we move that "add" logic elsewhere? It could be the responsibility of the shell to decide to focus it when the button is clicked. Here maybe: https://github.com/compose-ui/shell/blob/master/compose-shell.js#L49
